version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /tools/dashboard-ui
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /packages/pursers
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /packages/central
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /packages/client
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /packages/personal
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /packages/import
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /tools/wait-bridge
    schedule:
      interval: weekly
