/* Fleet route module: team. */
(function registerTeamView() {
  'use strict';
  let esc, pageHead, fleetData, hubWorkers, agentIdentity, agentMatchesFilters,
    agentDisplayState, workerForAgent, liveAgentCard, renderGuide, agentCountStrip,
    agentFilterBar, agentPoolScope, inactiveAgentDrawer, autonomousRows,
    autonomousStateLabel, autonomousObservationLabel;
  function useContext(context) {
    ({esc, pageHead, fleetData, hubWorkers, agentIdentity, agentMatchesFilters,
      agentDisplayState, workerForAgent, liveAgentCard, renderGuide, agentCountStrip,
      agentFilterBar, agentPoolScope, inactiveAgentDrawer, autonomousRows,
      autonomousStateLabel, autonomousObservationLabel} = context);
  }
function renderAgentsHub(){const records=[],seen=new Set();for(const [central,d] of Object.entries(fleetData)){for(const a of d.agents||[]){const key=`${central}/${agentIdentity(a)}/${a.agent_name||''}`;if(!seen.has(key))records.push({central,agent:a});seen.add(key)}}for(const [central,d] of Object.entries(hubWorkers)){const live=fleetData[central]?.agents||[];for(const w of d.workers||[]){const stable=Boolean(w.agent_id||w.principal_id),represented=live.some(a=>agentIdentity(a)===agentIdentity(w));if(represented||(!stable&&live.some(a=>a.agent_name===w.name)))continue;const work=w.current_work||[],a={agent_name:w.name,agent_id:w.agent_id,principal_id:w.principal_id,pool_status:work.length?'busy':'offline',boards:[...new Set(work.map(x=>x.board_id).filter(Boolean))],seats:[],last_seen:w.last_seen||null},key=`${central}/${agentIdentity(a)}/${a.agent_name||''}`;if(!seen.has(key))records.push({central,agent:a});seen.add(key)}}const visible=records.filter(agentMatchesFilters),cards=visible.sort((a,b)=>{const rank={working:0,available:1,connected:2,stale:3,offline:4},as=agentDisplayState(a.agent,workerForAgent(a.central,a.agent)),bs=agentDisplayState(b.agent,workerForAgent(b.central,b.agent));return rank[as]-rank[bs]||String(a.agent.agent_name||'').localeCompare(String(b.agent.agent_name||''))||a.central.localeCompare(b.central)||agentIdentity(a.agent).localeCompare(agentIdentity(b.agent))}).map(x=>liveAgentCard(x.central,x.agent)),empty=records.length===0?'No seats exist in the covered boards.':'No seats match the selected filters.',scope=agentPoolScope(),unknownModel=Object.values(fleetData).reduce((total,d)=>total+Number(d.pool_summary?.unknown_model||0),0),action='<div class="agent-actions"><button id="new-agent" class="primary-action" type="button">+ New agent</button></div>';return`<div class="agents-hub">${pageHead('Agents','Unified agent pool','Live status, held work, leases, and source-backed seat metadata.',action)}${renderGuide()}<section class="strip agent-model-summary" aria-label="Model attribution coverage"><div class="metric"><span>Unknown model</span><b>${esc(unknownModel)}</b></div></section>${agentCountStrip(records)}${agentFilterBar(records)}${scope}<p id="hub-agent-status" class="muted">Showing ${cards.length} of ${records.length} seats</p><section class="agent-grid dense-agent-grid" data-pursers-panel="agents" data-pursers-state="${cards.length?'ready':'empty'}">${cards.join('')||`<p class="empty">${esc(empty)}</p>`}</section>${inactiveAgentDrawer()}</div>`}
  function renderAutonomousTeam(){const cards=autonomousRows().filter(row=>row.data?.config).map(({central,board,data})=>{const desired=data.config.desired?.capacity||{},actual=data.actual_state_available?data.actual_state?.capacity||{}:{},roles=['worker','reviewer','acp_worker'],observation=autonomousObservationLabel(data);return `<article class="card" data-pursers-autonomous-team="${esc(board.board_id)}"><div class="section-title"><div><p class="eyebrow">${esc(board.label)} · ${esc(central)}</p><h3>Desired versus actual</h3></div><span class="status">${esc(autonomousStateLabel(data.effective_state))}</span></div><p class="meta" data-autonomous-observation="${esc(data.actual_state_status||'unavailable')}">Actual observation ${esc(observation)}</p><div class="autonomous-capacity">${roles.map(role=>{const target=desired[role]?.target??0,observed=actual[role],running=observed?(observed.ready||0)+(observed.busy||0):null;return `<div><b>${esc(role.replace('_',' '))}</b><p>Desired ${esc(target)}</p><span class="meta">Actual ${running===null?esc(observation):esc(running)}${observed?` · starting ${esc(observed.starting||0)} · unhealthy ${esc(observed.unhealthy||0)}`:''}</span></div>`}).join('')}</div><p class="meta">Host ${esc(data.config.host_runtime?.agent_process_ceiling||'—')} agent processes · ${esc(data.config.host_runtime?.total_process_ceiling||'—')} total ceiling · board concurrency ${esc(data.config.desired?.board_concurrency||'—')}</p></article>`}).join('');return `<section class="autonomous-grid" aria-label="Autonomous Butler fleet state">${cards||'<article class="card"><h3>Autonomous capacity</h3><p class="empty">No provisioned autonomous board state.</p></article>'}</section>`}
  globalThis.FleetViewModules.register({
    id: 'team',
    owns: [
      'agent roster',
    'seat filters',
    'autonomous butler status'
    ],
    render(context) { useContext(context); return renderAgentsHub() + renderAutonomousTeam(); }
  });
})();
