"""Public API for the namespaced On Board client distribution."""

from .client import (
    DEFAULT_EVENT_KINDS,
    GENERATION_META_KEY,
    BoardClient,
    BoardClientError,
    JoinedIdentity,
    ScrubRejectedError,
)
from .personal_profile import (
    PERSONAL_REVIEW_POLICY,
    PROFILE_ENV,
    PersonalContext,
    PersonalProfile,
    PersonalProfileError,
    ProfileSecurityError,
    bootstrap_personal_review_policy,
    central_environment,
    default_profiles_root,
    doctor_identity_summary,
    ensure_personal_profile,
    load_personal_profile,
    profile_path_for_project,
    read_capability,
    resolve_personal_context,
    rotate_personal_capability,
    select_personal_profile,
)

__all__ = [
    "BoardClient",
    "BoardClientError",
    "DEFAULT_EVENT_KINDS",
    "GENERATION_META_KEY",
    "JoinedIdentity",
    "PERSONAL_REVIEW_POLICY",
    "PROFILE_ENV",
    "PersonalContext",
    "PersonalProfile",
    "PersonalProfileError",
    "ProfileSecurityError",
    "ScrubRejectedError",
    "bootstrap_personal_review_policy",
    "central_environment",
    "default_profiles_root",
    "doctor_identity_summary",
    "ensure_personal_profile",
    "load_personal_profile",
    "profile_path_for_project",
    "read_capability",
    "resolve_personal_context",
    "rotate_personal_capability",
    "select_personal_profile",
]
