"""Warm Guided Home presentation layer for the loopback Fleet dashboard."""

from __future__ import annotations


WARM_GUIDED_HOME_CSS = r"""
:root,:root[data-theme="light"]{color-scheme:light;--bg:#f7f4ee;--panel:#fff;--panel2:#fbfaf7;--line:#e6e0d5;--text:#26332f;--muted:#66736d;--good:#4d9a7c;--warn:#9b7035;--bad:#a85846;--accent:#367568;--sidebar:238px;--warm-soft:#f4f0e8;--warm-action:#e8f2ed;--warm-danger:#f8e4d9;--shadow:0 8px 30px rgb(72 63 48 / 5%)}
:root[data-theme="dark"]{color-scheme:dark;--bg:#111815;--panel:#18211d;--panel2:#202b26;--line:#34433c;--text:#edf4f0;--muted:#a6b5ad;--good:#73c6a5;--warn:#e0b86d;--bad:#e29888;--accent:#83c2b4;--warm-soft:#202b26;--warm-action:#203a32;--warm-danger:#3b2823;--shadow:0 12px 34px rgb(0 0 0 / 22%)}
body{font-family:"DM Sans",ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:var(--bg)}h1,h2,h3,h4{font-family:"Manrope",ui-sans-serif,system-ui,sans-serif}.app-shell{max-width:1480px;margin:auto;background:var(--bg)}
.sidebar{background:var(--panel2);border-color:var(--line);padding:28px 20px}.brand{min-height:44px;padding:0;gap:12px}.brand-mark{width:40px;height:40px;border:1px solid color-mix(in srgb,var(--accent) 35%,var(--line));border-radius:14px;background:var(--warm-action);color:var(--accent);box-shadow:none}.brand-copy{display:grid;line-height:1.15}.brand-copy small{margin-top:4px;color:var(--muted);font-size:11px;font-weight:500}
.context-switcher{padding:10px;border:1px solid var(--line);border-radius:16px;background:var(--warm-soft)}.context-label{display:block;margin:0 4px 7px;color:var(--muted);font-size:10px;font-weight:800;letter-spacing:.14em;text-transform:uppercase}.context-option{display:flex;align-items:center;gap:9px;min-height:44px;padding:8px 10px;border-radius:12px;color:var(--muted);font-size:12px;font-weight:700}.context-option.active{background:var(--panel);color:var(--text);box-shadow:var(--shadow)}.context-dot{width:8px;height:8px;margin-left:auto;border-radius:50%;background:var(--good)}
.primary-nav{gap:3px}.primary-nav a{min-height:44px;border-radius:12px;padding:10px 12px;font-size:13px;font-weight:600;letter-spacing:0}.primary-nav a.active{background:var(--warm-action);color:var(--accent);box-shadow:none}.primary-nav a.active::after{content:"";width:7px;height:7px;margin-left:auto;border-radius:50%;background:var(--accent)}.nav-icon{width:22px;color:var(--muted);font-size:15px}.primary-nav a.active .nav-icon{color:var(--accent)}
.sidebar-foot{padding:14px;border:1px solid var(--line);border-radius:16px;background:var(--panel);line-height:1.55}.sidebar-foot b{display:block;color:var(--text);font-size:12px}.sidebar-foot span{display:block;margin-top:3px}.app-shell>main{padding:28px clamp(18px,3.2vw,48px)}.app-shell>main>.top{align-items:center;padding:0 0 22px}.app-shell>main>.top h1{font-size:16px;letter-spacing:-.01em}.app-shell>main>.top>div:first-child .muted{font-size:12px}
.view-controls button,#filter,.toolbar select,.toolbar input,.toolbar button,.button,.card-actions a,.agent-actions button,.primary-action,.attention-actions button,.seat-form input,.seat-form select,.seat-form button,.seat-actions button,.seat-toolbar button,.dispatch-form input,.dispatch-form button,.intake-form textarea,.intake-form button,.intake-actions button{min-height:44px;border-radius:12px}.view-controls button{min-width:44px}.app-shell>main a{display:inline-flex;align-items:center;min-height:44px}.page-head{align-items:start;margin:34px 0 22px}.page-head h2{font-size:clamp(28px,3.2vw,42px);line-height:1.08}.page-head .muted{max-width:68ch;margin-top:8px;font-size:14px;line-height:1.65}.eyebrow{color:var(--accent)}
.health-card,.attention-card,.agent-card,.ops-card,.board-card,.metric,.card{border-color:var(--line);border-radius:22px;background:var(--panel);box-shadow:var(--shadow)}.health-card,.attention-card,.agent-card,.ops-card,.board-card{padding:20px}.guided-hero{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(260px,.8fr);gap:18px;margin-bottom:22px}.guided-next{padding:26px;border:1px solid color-mix(in srgb,var(--accent) 22%,var(--line));border-radius:24px;background:var(--warm-action)}.guided-next h3{margin-top:7px;font-size:clamp(21px,2.4vw,30px)}.guided-next p{max-width:58ch;margin-top:8px;color:var(--muted)}.guided-next .card-actions{justify-content:flex-start;margin-top:18px}.guided-next .primary-action{background:var(--accent);color:#fff}
.guided-summary{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.guided-summary div{padding:16px;border:1px solid var(--line);border-radius:18px;background:var(--panel)}.guided-summary span{display:block;color:var(--muted);font-size:11px}.guided-summary b{display:block;margin-top:5px;font-size:24px}.warm-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(290px,100%),1fr));gap:16px}.warm-section{margin-top:24px}.warm-section>.section-title{margin:0 0 12px}.warm-list{display:grid;gap:0}.warm-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:14px;align-items:center;min-height:64px;padding:12px 0;border-top:1px solid var(--line)}.warm-row:first-child{border-top:0}.warm-row p,.warm-row .meta{margin-top:4px}.warm-row-actions{display:flex;flex-wrap:wrap;justify-content:flex-end;gap:7px}
.truth-strip{display:flex;flex-wrap:wrap;gap:7px;margin:0 0 16px}.truth-strip .status{min-height:28px;padding:5px 9px}.truth-strip .status:first-child{background:var(--warm-action);color:var(--accent)}.settings-groups{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(310px,100%),1fr));gap:16px}.settings-group{display:grid;align-content:start;gap:10px}.settings-group .card-actions{justify-content:flex-start}.empty-guidance{padding:28px;border:1px dashed var(--line);border-radius:22px;background:var(--panel);text-align:center}.empty-guidance h3{font-size:20px}.empty-guidance p{max-width:56ch;margin:8px auto 18px;color:var(--muted)}
.empty-guidance .card-actions{justify-content:center}.status{font-weight:700}.status[data-tone="danger"]{background:var(--warm-danger);color:var(--bad)}.table-scroll{border-radius:14px}th{font-size:11px;font-weight:800;letter-spacing:.06em;text-transform:uppercase}td{padding-top:12px;padding-bottom:12px}:focus-visible{outline:3px solid color-mix(in srgb,var(--accent) 70%,white);outline-offset:3px;box-shadow:none}
.warm-row>div:first-child{display:grid;justify-items:start;gap:3px}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{animation:none!important;scroll-behavior:auto!important;transition:none!important}}@media(max-width:900px){.guided-hero{grid-template-columns:1fr}.board-card{grid-template-columns:1fr}.card-actions{justify-content:flex-start}}@media(max-width:800px){.sidebar{position:sticky;top:0;display:block;max-width:100%;padding:8px 10px;background:var(--panel);overflow:hidden}.brand,.context-switcher,.sidebar-foot{display:none}.primary-nav{display:flex;max-width:100%;gap:4px;overflow-x:auto;overscroll-behavior-inline:contain;scrollbar-width:thin}.primary-nav a{flex:0 0 auto;min-width:92px;padding:9px 10px}.primary-nav a.active{box-shadow:inset 0 -3px var(--accent)}.primary-nav a.active::after{display:none}.nav-icon{display:inline-block}.app-shell>main{padding:14px;max-width:100%;overflow:hidden}.page-head{margin-top:24px}.warm-row{grid-template-columns:1fr}.warm-row-actions{justify-content:flex-start}.table-scroll{max-width:calc(100vw - 28px)}}@media(max-width:430px){.guided-next{padding:20px}.guided-summary{grid-template-columns:1fr 1fr}.page-head h2{font-size:30px}.search-results{right:auto;left:0;width:calc(100vw - 28px)}}
"""


WARM_GUIDED_HOME_SCRIPT = r"""
const warmLegacyRoute=route,warmHubKinds=new Set(['home','projects','work','team','approvals','activity','settings']);
route=function(){const match=location.hash.match(/^#\/(home|projects|work|team|approvals|activity|settings)$/);return match?{kind:match[1]}:warmLegacyRoute()};for(const kind of warmHubKinds)hubKinds.add(kind);
navKind=function(){const current=route();if(!current)return'home';if(warmHubKinds.has(current.kind))return current.kind;if(current.kind==='boards')return'projects';if(current.kind==='agents')return'team';if(['operations','seats','config','overhead','workers'].includes(current.kind))return'settings';if(current.kind==='board')return'work';return'home'};
function warmBoards(){const rows=[];for(const [central,data] of Object.entries(fleetData))for(const board of data.boards||[])rows.push({central,board});return rows}
function warmTickets(){const rows=[];for(const item of warmBoards())for(const ticket of item.board.tickets||[])rows.push({...item,ticket});return rows}
function warmTruthStrip(){return '<div class="truth-strip" aria-label="Data boundaries"><span class="status">WORK</span><span class="status">Local</span><span class="status">Bounded data</span><span class="status">Guarded writes</span></div>'}
function warmNextAction(){const human=humanRequestRows()[0];if(human)return{eyebrow:'Waiting for you',title:human.h.message||'A teammate needs your decision',copy:`${human.board.label} is paused until a human answer is recorded.`,href:ticketHref(human.central,human.board.board_id,human.h.ticket_id),label:'Review request'};const submitted=warmTickets().find(item=>item.ticket.status==='submitted');if(submitted)return{eyebrow:'Ready for review',title:submitted.ticket.title||submitted.ticket.id,copy:`${submitted.board.label} has work waiting for an independent decision.`,href:ticketHref(submitted.central,submitted.board.board_id,submitted.ticket.id),label:'Open submitted work'};const open=warmTickets().find(item=>item.ticket.status==='open');if(open)return{eyebrow:'Next useful action',title:open.ticket.title||open.ticket.id,copy:`Open in ${open.board.label} to inspect ownership, route, and dispatch state.`,href:ticketHref(open.central,open.board.board_id,open.ticket.id),label:'Open work'};const item=warmBoards()[0];return item?{eyebrow:'Everything is calm',title:'No work needs attention',copy:'Your connected projects are healthy. Start with a board when you are ready.',href:boardHref(item.central,item.board.board_id),label:'Open a project'}:null}
function renderWarmHome(){const boards=warmBoards(),tickets=warmTickets();if(!boards.length)return `${pageHead('Home','Welcome to your work home','Connect one project, then describe work and let the board route it safely.')}${warmTruthStrip()}<section class="empty-guidance"><h3>Connect your first project</h3><p>Add a project in Settings. Pursers will prepare its board, protected doors, and isolated Fleet clone.</p><div class="card-actions"><a class="primary-action" href="#/settings">Open Settings</a></div></section>`;const next=warmNextAction(),active=tickets.filter(item=>['claimed','in_progress','creating_report'].includes(item.ticket.status)).length,submitted=tickets.filter(item=>item.ticket.status==='submitted').length,attention=reconcileAttention().length,hero=next?`<article class="guided-next"><p class="eyebrow">${esc(next.eyebrow)}</p><h3>${esc(next.title)}</h3><p>${esc(next.copy)}</p><div class="card-actions"><a class="primary-action" href="${esc(next.href)}">${esc(next.label)}</a><a href="#/work">View all work</a></div></article>`:'';return `${pageHead('Home','Good to see your Team','Start with the next safe action, then scan project health and progress.')}${warmTruthStrip()}<section class="guided-hero">${hero}<div class="guided-summary"><div><span>Projects</span><b>${boards.length}</b></div><div><span>Working</span><b>${active}</b></div><div><span>Review ready</span><b>${submitted}</b></div><div><span>Needs attention</span><b>${attention}</b></div></div></section><section class="warm-grid">${centralLabels.map(label=>{const data=fleetData[label],summary=data?.pool_summary||{};return `<article class="health-card"><div class="signal"><span class="signal-dot ${data?'':'bad'}"></span><b>${esc(label)}</b><span class="status">${data?'connected':'reconnecting'}</span></div><p class="meta">${data?'Independent central trust domain':'Last-known data stays labeled stale.'}</p><div class="health-metrics"><span>Working<b>${esc(summary.busy||0)}</b></span><span>Ready<b>${esc(summary.available||0)}</b></span><span>Stale<b>${esc(summary.stale||0)}</b></span></div></article>`}).join('')}</section>${renderWaitingForYou()}`}
function renderWarmProjects(){const cards=warmBoards().map(({central,board})=>{const counts=board.counts||{},total=Object.values(counts).reduce((sum,value)=>sum+numberCount(value),0),truncation=board.snapshot_truncation,limited=truncation&&truncation.total>truncation.returned;return `<article class="board-card"><div><p class="eyebrow">${esc(central)}</p><h3>${esc(board.label)}</h3><p class="meta">${esc(board.board_id)} · ${esc(total)} visible tickets${limited?` · bounded ${esc(truncation.returned)} of ${esc(truncation.total)}`:''}</p></div><div class="counts">${Object.entries(counts).map(([key,value])=>`<span class="pill">${esc(key.replaceAll('_',' '))} <b>${esc(value)}</b></span>`).join('')}</div><div class="card-actions"><a class="primary-action" href="${boardHref(central,board.board_id)}">Open project</a><a href="${boardHref(central,board.board_id,'routes')}">Routes</a></div></article>`}).join('');return `${pageHead('Projects','Connected projects','Choose a project, check its connection health, or add another from Settings.')}${warmTruthStrip()}<section class="boards-list">${cards||'<div class="empty-guidance"><h3>No connected projects</h3><p>Add one project from Settings to create its board and protected connection.</p><div class="card-actions"><a class="primary-action" href="#/settings">Add project</a></div></div>'}</section>`}
function renderWarmWork(){const groups=['open','claimed','in_progress','creating_report','submitted','needs_human','closed','rejected','canceled','terminated'],tickets=warmTickets(),known=new Set(groups),sections=[];for(const status of groups){const items=tickets.filter(item=>item.ticket.status===status);if(!items.length)continue;sections.push(`<section class="card warm-section"><div class="section-title"><h3>${esc(status.replaceAll('_',' '))}</h3><span class="status">${items.length}</span></div><div class="warm-list">${items.map(({central,board,ticket})=>`<div class="warm-row"><div><a class="id" href="${ticketHref(central,board.board_id,ticket.id)}">${esc(ticket.id)}</a><b>${esc(ticket.title||'(untitled)')}</b><p class="meta">${esc(board.label)} · ${esc(central)} · ${esc(ticket.claimed_by||'unclaimed')}</p></div><div class="warm-row-actions"><a class="button" href="${ticketHref(central,board.board_id,ticket.id)}">Details</a><a class="button" href="${boardHref(central,board.board_id,'flow')}">Flow</a></div></div>`).join('')}</div></section>`)}const unknown=tickets.filter(item=>!known.has(item.ticket.status));if(unknown.length)sections.push(`<section class="card warm-section"><div class="section-title"><h3>Other states</h3><span class="status">${unknown.length}</span></div><p class="muted">Unknown states remain visible rather than being silently grouped.</p>${unknown.map(({central,board,ticket})=>`<div class="warm-row"><a class="id" href="${ticketHref(central,board.board_id,ticket.id)}">${esc(ticket.id)}</a><span class="status">${esc(ticket.status)}</span></div>`).join('')}</section>`);return `${pageHead('Work','Work across every project','Follow open, active, review-ready, completed, ended, and unknown ticket states. Ticket detail preserves timeline, changes, flow, routes, leases, and handoffs.')}${warmTruthStrip()}${sections.join('')||'<div class="empty-guidance"><h3>No work yet</h3><p>Choose a project and use its guarded intake to describe the outcome you need.</p><div class="card-actions"><a class="primary-action" href="#/projects">Choose a project</a></div></div>'}`}
function renderWarmApprovals(){const submitted=warmTickets().filter(item=>item.ticket.status==='submitted'),reviewRows=submitted.map(({central,board,ticket})=>`<div class="warm-row"><div><a class="id" href="${ticketHref(central,board.board_id,ticket.id)}">${esc(ticket.id)}</a><b>${esc(ticket.title||'(untitled)')}</b><p class="meta">${esc(board.label)} · independent review required</p></div><div class="warm-row-actions"><a class="button" href="${ticketHref(central,board.board_id,ticket.id)}">Inspect evidence</a></div></div>`).join(''),intakeLinks=warmBoards().map(({central,board})=>`<a class="button" href="${boardHref(central,board.board_id)}">${esc(board.label)} intake</a>`).join('');return `${pageHead('Approvals','Decisions that need judgment','Human requests, submitted review, and guarded intake stay distinct. Destructive actions keep their confirmation boundaries.')}${warmTruthStrip()}${renderWaitingForYou()}<section class="card warm-section"><div class="section-title"><h3>Submitted for independent review</h3><span class="status">${submitted.length}</span></div><div class="warm-list">${reviewRows||'<p class="empty">Nothing is waiting for review.</p>'}</div></section><section class="card warm-section"><div class="section-title"><h3>Intake queues</h3><span class="status">source-backed</span></div><p class="muted">Open a project to view, approve, decline, or create intake through the guarded endpoint.</p><div class="card-actions">${intakeLinks||'<span class="empty">No project intake queues.</span>'}</div></section>`}
function renderWarmActivity(){const recent=warmTickets().filter(item=>item.ticket.updated_at).sort((a,b)=>new Date(b.ticket.updated_at)-new Date(a.ticket.updated_at)).slice(0,20),rows=recent.map(({central,board,ticket})=>`<div class="warm-row"><div><b>${esc(ticket.title||ticket.id)}</b><p class="meta">${esc(fmt(ticket.updated_at))} · ${esc(ticket.status)} · ${esc(board.label)}</p></div><div class="warm-row-actions"><a class="button" href="${ticketHref(central,board.board_id,ticket.id)}">Ticket</a><a class="button" href="${boardHref(central,board.board_id,'timeline')}">Timeline</a><a class="button" href="${boardHref(central,board.board_id,'changes')}">Changes</a></div></div>`).join('');return `${pageHead('Activity','Bounded activity','Recent ticket state comes from the bounded Fleet snapshot. Open a board timeline for actor and event provenance; older events may exist.')}${warmTruthStrip()}<section class="card"><div class="section-title"><h3>Recent state changes</h3><span class="status">up to 20 shown</span></div><div class="warm-list">${rows||'<p class="empty">No recent ticket state is visible.</p>'}</div></section><section class="warm-grid warm-section">${warmBoards().map(({central,board})=>`<article class="card"><p class="eyebrow">${esc(central)}</p><h3>${esc(board.label)}</h3><p class="muted">Actor provenance, cursor, has-more, dropped, and resync state remain in board detail.</p><div class="card-actions"><a href="${boardHref(central,board.board_id,'timeline')}">Timeline</a><a href="${boardHref(central,board.board_id,'changes')}">Changes</a><a href="${boardHref(central,board.board_id,'routes')}">Routes</a></div></article>`).join('')}</section>`}
function renderWarmSettings(){const cards=centralLabels.map(central=>`<article class="card settings-group"><p class="eyebrow">${esc(central)}</p><h3>Coordinator & diagnostics</h3><p class="muted">Policy, bounded protocol overhead, provenance routes, and local API worker controls.</p><div class="card-actions"><a class="button" href="${centralHref(central,'config')}">Coordinator config</a><a class="button" href="${centralHref(central,'workers')}">Workers</a><a class="button" href="${centralHref(central,'overhead')}">Overhead</a></div></article>`).join('');return `${pageHead('Settings','Connections and advanced operations','Every mutation remains behind its existing plan, permission, redaction, idempotency, and confirmation guard.')}${warmTruthStrip()}<section class="settings-groups"><article class="card settings-group"><p class="eyebrow">Projects & protected doors</p><h3>Connections</h3><p class="muted">Add projects, inspect registry clones, copy a door once, or plan rotation without displaying stored secrets.</p><div class="card-actions"><a class="primary-action" href="#/seats">Open connections</a></div></article><article class="card settings-group"><p class="eyebrow">Team & seats</p><h3>Runtime setup</h3><p class="muted">Seat inventory, Doctor, bridge upgrades, dispatch policy, offers, and lifecycle operations.</p><div class="card-actions"><a class="button" href="#/seats">Seats & dispatch</a><a class="button" href="#/team">Team readiness</a></div></article>${cards}<article class="card settings-group"><p class="eyebrow">Release operations</p><h3>Guarded plans</h3><p class="muted">Stage, publish, kickstart, restart, and registry operations show exact scope and require explicit confirmation.</p><div class="card-actions"><a class="button" href="#/seats">Review operations</a></div></article></section>`}
const renderWarmHubBefore=renderHub;renderHub=function(){const host=document.querySelector('#central-sections'),kind=navKind(),renderers={home:renderWarmHome,projects:renderWarmProjects,work:renderWarmWork,team:renderAgentsHub,approvals:renderWarmApprovals,activity:renderWarmActivity,settings:renderWarmSettings};if(!renderers[kind])return renderWarmHubBefore();host.innerHTML=renderers[kind]();const newest=Object.values(fleetData).map(data=>data.generated_at).filter(Boolean).sort().at(-1);document.querySelector('#state').textContent=newest?`Updated ${fmt(newest)} · bounded view`:'Connecting to centrals…';bindInteractive(host);bindHub();renderSearchResults();syncNav()};renderFleet=renderHub;
const warmSyncHubBefore=syncHub;syncHub=function(){const current=route();if(!current||warmHubKinds.has(current.kind)||['boards','agents','operations'].includes(current.kind)){document.querySelector('#home-view').hidden=false;document.querySelector('#detail-view').hidden=true;document.querySelector('#config-view').hidden=true;document.querySelector('#workers-view').hidden=true;renderHub();refreshHubExtras();return}warmSyncHubBefore()};const warmRefreshHubExtrasBefore=refreshHubExtras;refreshHubExtras=async function(){await warmRefreshHubExtrasBefore();if(warmHubKinds.has(navKind())&&!refreshPaused())renderHub()};theme='light';applyPreferences();syncNav();syncHub();
"""


OLD_SIDEBAR = r"""<aside class="sidebar" aria-label="Primary navigation"><a class="brand" href="#/"><span class="brand-mark">P</span><span>Pursers Fleet</span></a><nav class="primary-nav"><a data-nav="overview" href="#/"><span class="nav-icon">⌂</span>Overview</a><a data-nav="boards" href="#/boards"><span class="nav-icon">▦</span>Boards</a><a data-nav="agents" href="#/agents"><span class="nav-icon">◎</span>Agents</a><a data-nav="operations" href="#/operations"><span class="nav-icon">⚙</span>Operations</a><a data-nav="seats" href="#/seats"><span class="nav-icon">⌘</span>Config</a></nav><div class="sidebar-foot">Loopback control plane<br>bounded reads · guarded writes</div></aside>"""
WARM_SIDEBAR = r"""<aside class="sidebar" aria-label="Primary navigation"><a class="brand" href="#/home"><span class="brand-mark">P</span><span class="brand-copy">Pursers Fleet<small>Your calm work home</small></span></a><section class="context-switcher" aria-label="Workspace context"><span class="context-label">Context</span><span class="context-option active">▣ <span>WORK</span><span class="context-dot" aria-hidden="true"></span></span><span class="context-option">⌂ <span>PERSONAL</span></span></section><nav class="primary-nav"><a data-nav="home" href="#/home"><span class="nav-icon">⌂</span>Home</a><a data-nav="projects" href="#/projects"><span class="nav-icon">▦</span>Projects</a><a data-nav="work" href="#/work"><span class="nav-icon">✓</span>Work</a><a data-nav="team" href="#/team"><span class="nav-icon">◎</span>Team</a><a data-nav="approvals" href="#/approvals"><span class="nav-icon">◇</span>Approvals</a><a data-nav="activity" href="#/activity"><span class="nav-icon">↻</span>Activity</a><a data-nav="settings" href="#/settings"><span class="nav-icon">⚙</span>Settings</a></nav><div class="sidebar-foot"><b>Local Fleet control</b><span>Bounded reads · guarded writes<br>Secrets stay redacted</span></div></aside>"""


def apply_warm_guided_home(html: str) -> str:
    """Apply the approved seven-destination visual shell to the final HTML."""
    if OLD_SIDEBAR not in html:
        raise ValueError("Fleet dashboard sidebar contract changed")
    html = html.replace(OLD_SIDEBAR, WARM_SIDEBAR, 1)
    html = html.replace("</style>", WARM_GUIDED_HOME_CSS + "\n</style>", 1)
    return html.replace("</script></body>", "</script><script>\n" + WARM_GUIDED_HOME_SCRIPT + "\n</script></body>", 1)
