"""Provision a private, local Pursers Central quickstart instance."""

from __future__ import annotations

import json
import os
import re
import secrets
import stat
import tempfile
import time
from pathlib import Path
from typing import Mapping

import jwt
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from jwt.algorithms import RSAAlgorithm


PROFILE_NAME = "profile.env"
KEY_NAME = "signing-key.pem"
JWKS_NAME = "jwks.json"
ADMIN_TOKEN_NAME = "admin.jwt"
WORKER_TOKEN_NAME = "worker.jwt"
DATA_NAME = "data"
MANAGED_FILES = (
    PROFILE_NAME,
    KEY_NAME,
    JWKS_NAME,
    ADMIN_TOKEN_NAME,
    WORKER_TOKEN_NAME,
)
BOARD_ID_RE = re.compile(r"^[A-Za-z0-9._-]{1,80}$")
PROFILE_KEYS = frozenset(
    {
        "ONBOARD_CENTRAL_HOST",
        "ONBOARD_CENTRAL_PORT",
        "ONBOARD_CENTRAL_DATA_DIR",
        "CENTRAL_JWT_ISSUER",
        "CENTRAL_JWT_AUDIENCE",
        "CENTRAL_JWKS_PATH",
        "PURSERS_BOARD_ID",
        "PURSERS_ADMIN_TOKEN_FILE",
        "PURSERS_WORKER_TOKEN_FILE",
    }
)
RUNTIME_PROFILE_KEYS = frozenset(
    {
        "ONBOARD_CENTRAL_HOST",
        "ONBOARD_CENTRAL_PORT",
        "ONBOARD_CENTRAL_DATA_DIR",
        "CENTRAL_JWT_ISSUER",
        "CENTRAL_JWT_AUDIENCE",
        "CENTRAL_JWKS_PATH",
    }
)


class QuickstartError(RuntimeError):
    """A secret-safe quickstart provisioning or profile error."""


def _private_root(value: Path) -> Path:
    root = value.expanduser().absolute()
    if root == Path(root.anchor):
        raise QuickstartError("instance directory must not be a filesystem root")
    for candidate in (root, *root.parents):
        if os.path.lexists(candidate) and candidate.is_symlink():
            raise QuickstartError("instance directory and its parents must not be symlinks")
    if root.exists() and not root.is_dir():
        raise QuickstartError("instance path exists and is not a directory")
    return root


def _atomic_private_write(path: Path, content: bytes) -> None:
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "wb", closefd=True) as stream:
            descriptor = -1
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
        os.chmod(path, 0o600)
        directory = os.open(path.parent, os.O_RDONLY)
        try:
            os.fsync(directory)
        finally:
            os.close(directory)
    except OSError as exc:
        raise QuickstartError(f"cannot write private file {path}") from exc
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _public_jwk(private_key: rsa.RSAPrivateKey, kid: str) -> dict[str, object]:
    public = RSAAlgorithm.to_jwk(private_key.public_key(), as_dict=True)
    public.update({"kid": kid, "alg": "RS256", "use": "sig"})
    return public


def _token(
    private_key: rsa.RSAPrivateKey,
    *,
    kid: str,
    issuer: str,
    audience: str,
    scopes: tuple[str, ...],
    board_id: str | None,
) -> str:
    issued_at = int(time.time())
    claims: dict[str, object] = {
        "iss": issuer,
        "sub": "local-board-owner",
        "aud": audience,
        "resource": audience,
        "scope": " ".join(scopes),
        "client_id": "pursers-central-quickstart",
        "iat": issued_at,
        "nbf": issued_at - 5,
        "exp": issued_at + 365 * 24 * 60 * 60,
        "jti": secrets.token_urlsafe(24),
    }
    if board_id is not None:
        claims["pursers_board"] = board_id
    return jwt.encode(
        claims,
        private_key,
        algorithm="RS256",
        headers={"kid": kid},
    )


def _profile(values: Mapping[str, str]) -> bytes:
    lines = [
        "# Generated by pursers-central init. Read directly by pursers-central run.",
        *(f"{key}={values[key]}" for key in sorted(values)),
    ]
    return ("\n".join(lines) + "\n").encode("utf-8")


def init_instance(
    root_value: Path,
    *,
    port: int = 8766,
    board_id: str = "pursers-local",
    force: bool = False,
) -> dict[str, Path]:
    """Create or explicitly rotate one local quickstart instance."""
    if not 1 <= port <= 65_535:
        raise QuickstartError("port must be between 1 and 65535")
    if not BOARD_ID_RE.fullmatch(board_id):
        raise QuickstartError(f"board must match {BOARD_ID_RE.pattern}")
    root = _private_root(root_value)
    root.mkdir(mode=0o700, parents=True, exist_ok=True)
    os.chmod(root, 0o700)
    data_dir = root / DATA_NAME
    if os.path.lexists(data_dir) and data_dir.is_symlink():
        raise QuickstartError("data directory must not be a symlink")
    data_dir.mkdir(mode=0o700, exist_ok=True)
    os.chmod(data_dir, 0o700)

    paths = {name: root / name for name in MANAGED_FILES}
    existing = [path for path in paths.values() if os.path.lexists(path)]
    for path in existing:
        if path.is_symlink() or not path.is_file():
            raise QuickstartError(f"managed path is not a regular file: {path}")
    if existing and not force:
        raise QuickstartError(
            "refusing to overwrite existing quickstart credentials; pass --force"
        )

    host = "127.0.0.1"
    audience = f"http://{host}:{port}/mcp"
    issuer = f"http://{host}:{port}/quickstart"
    kid = f"quickstart-{secrets.token_hex(16)}"
    private_key = rsa.generate_private_key(public_exponent=65_537, key_size=2_048)
    private_pem = private_key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    admin_token = _token(
        private_key,
        kid=kid,
        issuer=issuer,
        audience=audience,
        scopes=("board:read", "board:write", "board:review"),
        board_id=None,
    )
    worker_token = _token(
        private_key,
        kid=kid,
        issuer=issuer,
        audience=audience,
        scopes=("board:read", "board:write"),
        board_id=board_id,
    )
    profile_values = {
        "ONBOARD_CENTRAL_HOST": host,
        "ONBOARD_CENTRAL_PORT": str(port),
        "ONBOARD_CENTRAL_DATA_DIR": str(data_dir),
        "CENTRAL_JWT_ISSUER": issuer,
        "CENTRAL_JWT_AUDIENCE": audience,
        "CENTRAL_JWKS_PATH": str(paths[JWKS_NAME]),
        "PURSERS_BOARD_ID": board_id,
        "PURSERS_ADMIN_TOKEN_FILE": str(paths[ADMIN_TOKEN_NAME]),
        "PURSERS_WORKER_TOKEN_FILE": str(paths[WORKER_TOKEN_NAME]),
    }
    _atomic_private_write(paths[KEY_NAME], private_pem)
    _atomic_private_write(
        paths[JWKS_NAME],
        (json.dumps({"keys": [_public_jwk(private_key, kid)]}, sort_keys=True) + "\n").encode(),
    )
    _atomic_private_write(paths[ADMIN_TOKEN_NAME], (admin_token + "\n").encode())
    _atomic_private_write(paths[WORKER_TOKEN_NAME], (worker_token + "\n").encode())
    _atomic_private_write(paths[PROFILE_NAME], _profile(profile_values))
    return {"root": root, "data": data_dir, **paths}


def load_profile(root_value: Path) -> dict[str, str]:
    """Load and validate the non-shell quickstart runtime profile."""
    root = _private_root(root_value)
    profile_path = root / PROFILE_NAME
    try:
        info = profile_path.lstat()
        if not stat.S_ISREG(info.st_mode) or stat.S_IMODE(info.st_mode) != 0o600:
            raise QuickstartError("quickstart profile must be a regular 0600 file")
        rows = profile_path.read_text(encoding="utf-8").splitlines()
    except QuickstartError:
        raise
    except (OSError, UnicodeDecodeError) as exc:
        raise QuickstartError(f"cannot read quickstart profile {profile_path}") from exc
    values: dict[str, str] = {}
    for number, row in enumerate(rows, 1):
        if not row or row.startswith("#"):
            continue
        key, separator, value = row.partition("=")
        if not separator or key not in PROFILE_KEYS or not value or key in values:
            raise QuickstartError(f"invalid quickstart profile line {number}")
        values[key] = value
    missing = sorted(PROFILE_KEYS - values.keys())
    if missing:
        raise QuickstartError("quickstart profile is missing: " + ", ".join(missing))
    try:
        port = int(values["ONBOARD_CENTRAL_PORT"])
    except ValueError as exc:
        raise QuickstartError("quickstart profile port is invalid") from exc
    if not 1 <= port <= 65_535:
        raise QuickstartError("quickstart profile port is invalid")
    if values["ONBOARD_CENTRAL_HOST"] != "127.0.0.1":
        raise QuickstartError("quickstart profile host must be 127.0.0.1")
    expected_paths = {
        "ONBOARD_CENTRAL_DATA_DIR": root / DATA_NAME,
        "CENTRAL_JWKS_PATH": root / JWKS_NAME,
        "PURSERS_ADMIN_TOKEN_FILE": root / ADMIN_TOKEN_NAME,
        "PURSERS_WORKER_TOKEN_FILE": root / WORKER_TOKEN_NAME,
    }
    for key, expected in expected_paths.items():
        if Path(values[key]) != expected:
            raise QuickstartError(f"quickstart profile {key} does not match its instance")
    if not BOARD_ID_RE.fullmatch(values["PURSERS_BOARD_ID"]):
        raise QuickstartError("quickstart profile board is invalid")
    return values


def apply_runtime_profile(root: Path) -> dict[str, str]:
    """Apply only runtime settings; credential values never enter the environment."""
    profile = load_profile(root)
    for key in RUNTIME_PROFILE_KEYS:
        os.environ[key] = profile[key]
    return profile
